remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

description: "This website makes some visibility for my personal projects."

logo: assets/images/me.jpeg
linkedin_username: tristan-dietz
github_username: Pyrrha
# geolocation: "Nice, France"